# ~/.config/i3/bindings.conf

# Terminal
bindsym $mod+Return exec kitty

# Kill window
bindsym $mod+q kill

# Launcher
bindsym $mod+d exec rofi -show drun -theme ~/.config/rofi/launcher.rasi

# Movimiento de foco
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

bindsym $mod+Left  focus left
bindsym $mod+Down  focus down
bindsym $mod+Up    focus up
bindsym $mod+Right focus right

# Mover ventanas
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

bindsym $mod+Shift+Left  move left
bindsym $mod+Shift+Down  move down
bindsym $mod+Shift+Up    move up
bindsym $mod+Shift+Right move right

# Splits
bindsym $mod+h split h
bindsym $mod+v split v

# Fullscreen
bindsym $mod+f fullscreen toggle

# Layouts
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# Toggle floating
bindsym $mod+Shift+space floating toggle

# Cambiar entre tiling / floating
bindsym $mod+space focus mode_toggle

# Foco contenedor padre
bindsym $mod+a focus parent

# Recargar configuración
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart

# Salir de i3
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m '¿Salir de i3?' -B 'Sí' 'i3-msg exit'"

# Volumen
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym XF86AudioMute        exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute     exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Brillo
bindsym XF86MonBrightnessUp   exec brightnessctl s 10%+
bindsym XF86MonBrightnessDown exec brightnessctl s 10%-

# Bloquear pantalla
bindsym $mod+Escape exec --no-startup-id bash ~/.config/polybar/scripts/lockscreen.sh

# Captura de pantalla
bindsym Print             exec --no-startup-id flameshot full -p ~/Imágenes/
bindsym $mod+p            exec --no-startup-id maim -s | xclip -selection clipboard -t image/png
bindsym $mod+Shift+p      exec --no-startup-id flameshot gui
