# ~/.config/i3/general.conf

# Gaps externos: espacio entre el borde de la pantalla y las ventanas
gaps outer 3
# Gaps internos: espacio entre las ventanas entre sí
gaps inner 7

# Quitar la barra de título en todas las ventanas
for_window [class=".*"] border pixel 2

# Ejecutar scripts/aplicaciones al inicio
exec --no-startup-id dbus-update-activation-environment --systemd DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS
exec --no-startup-id /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1
exec --no-startup-id systemctl --user start gvfs-daemon.service
exec --no-startup-id dunst &
exec --no-startup-id udiskie --tray &
exec_always --no-startup-id bash ~/.config/polybar/launch.sh
exec_always --no-startup-id bash ~/.config/i3/wallpaper.sh
exec --no-startup-id picom --config ~/.config/picom/picom.conf -b
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id setxkbmap -layout es
exec --no-startup-id xss-lock --transfer-sleep-lock -- bash ~/.config/polybar/scripts/lockscreen.sh

# Mouse para mover ventanas flotantes
floating_modifier $mod
